export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_ANNONCE_STATE_CHANGE = 'USER_ANNONCE_STATE_CHANGE'
export const CLEAR_DATA = 'CLEAR_DATA'
export const USERS_ANNONCE_STATE_CHANGE = 'USERS_ANNONCE_STATE_CHANGE'
export const USERS_STATE_CHANGE = 'USERS_STATE_CHANGE'

 

